# Organization-wide pre-commit configuration
#     pre_commit_config_url: 'https://raw.githubusercontent.com/darkobas2/lint-test/main/.pre-commit-config.yaml'

repos:
  # ============================================================
  # Basic file hygiene
  # ============================================================
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: (^charts/.*/templates/|^templates/).*\.ya?ml$
      - id: end-of-file-fixer
        exclude: (^charts/.*/templates/|^templates/).*\.ya?ml$
      - id: check-yaml
        args: ['--allow-multiple-documents', '--unsafe']
        exclude: (^charts/.*/templates/|^templates/).*\.ya?ml$
      - id: check-json
      - id: pretty-format-json
        args: ['--autofix', '--indent=2', '--no-sort-keys']
        exclude: (package-lock\.json|\.terraform/)
      - id: check-xml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: detect-private-key

  # ============================================================
  # YAML linting
  # ============================================================
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.38.0
    hooks:
      - id: yamllint
        args: ['-c', '.yamllint']
        exclude: (^charts/.*/templates/|^templates/).*\.ya?ml$

  # ============================================================
  # YAML formatting
  # ============================================================
  - repo: https://github.com/google/yamlfmt
    rev: v0.21.0
    hooks:
      - id: yamlfmt
        args: ['-formatter', 'retain_line_breaks_single=true,line_length=120']
        exclude: (^charts/.*/templates/|^templates/).*\.ya?ml$

  # ============================================================
  # Shell script linting (optional - remove if not needed)
  # ============================================================
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        args: ['--severity=warning']

  # ============================================================
  # Markdown formatting (optional - remove if not needed)
  # ============================================================
  - repo: https://github.com/hukkin/mdformat
    rev: 0.7.21
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm          # GitHub Flavored Markdown
          - mdformat-tables       # Table formatting


